#!/usr/bin/env bash

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSIONS_FILE="$ROOT/tool-versions.txt"

trap 'printf "\nUpdate failed near line %s.\n" "${BASH_LINENO[0]}" >&2' ERR

heading() {
	printf '\n========================================\n'
	printf '%s\n' "$1"
	printf '========================================\n'
}

version_or_missing() {
	local command_name="$1"
	shift

	if command -v "$command_name" >/dev/null 2>&1; then
		"$@" 2>/dev/null | head -n 1
	else
		printf 'missing'
	fi
}

if [[ "$(id -u)" -eq 0 ]]; then
	printf 'Do not run this script with sudo.\n' >&2
	printf 'Run: ./update.sh\n' >&2
	exit 1
fi

cd "$ROOT"

heading "1/5 Updating Ubuntu"

sudo apt update
sudo apt full-upgrade -y
sudo apt autoremove -y
sudo apt autoclean

heading "2/5 Updating Node.js LTS"

export PNPM_HOME="$HOME/.local/share/pnpm"
export BUN_INSTALL="$HOME/.bun"
export PATH="$PNPM_HOME:$BUN_INSTALL/bin:$HOME/.local/share/fnm:$HOME/.local/bin:$PATH"

if command -v fnm >/dev/null 2>&1; then
	eval "$(fnm env --shell bash)"

	fnm install --lts --use

	NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
	fnm default "$NODE_MAJOR"
else
	printf 'fnm is not installed. Skipping Node update.\n'
fi

heading "3/5 Updating JavaScript and Python tools"

if command -v npm >/dev/null 2>&1; then
	npm install --global corepack@latest
	corepack enable
fi

if command -v pnpm >/dev/null 2>&1; then
	corepack prepare pnpm@latest --activate
fi

if command -v bun >/dev/null 2>&1; then
	bun upgrade
fi

if command -v uv >/dev/null 2>&1; then
	uv self update
fi

heading "4/5 Recording installed versions"

cat > "$VERSIONS_FILE" <<EOF_VERSIONS
# Generated by ./update.sh
# Last updated: $(date --iso-8601=seconds)

ubuntu=$(. /etc/os-release && printf '%s' "$PRETTY_NAME")
kernel=$(uname -r)
shell=$SHELL

git=$(version_or_missing git git --version)
gh=$(version_or_missing gh gh --version)
zsh=$(version_or_missing zsh zsh --version)
starship=$(version_or_missing starship starship --version)
fzf=$(version_or_missing fzf fzf --version)
zoxide=$(version_or_missing zoxide zoxide --version)
ripgrep=$(version_or_missing rg rg --version)
fd=$(version_or_missing fdfind fdfind --version)
bat=$(version_or_missing batcat batcat --version)
direnv=$(version_or_missing direnv direnv --version)

fnm=$(version_or_missing fnm fnm --version)
node=$(version_or_missing node node --version)
npm=$(version_or_missing npm npm --version)
pnpm=$(version_or_missing pnpm pnpm --version)
bun=$(version_or_missing bun bun --version)

python=$(version_or_missing python3 python3 --version)
uv=$(version_or_missing uv uv --version)
EOF_VERSIONS

cat "$VERSIONS_FILE"

heading "5/5 Checking dotfiles"

if [[ -x "$ROOT/dotfiles" ]]; then
	"$ROOT/dotfiles" doctor
fi

printf '\nUpdate complete.\n'
printf 'Review repository changes with:\n\n'
printf '  cd %q && git status\n\n' "$ROOT"
printf 'This script does not commit or push automatically.\n'
